name: Docker container using github actions 

on:      
  push:
    branches:
    - main

jobs:
  Dockerconfigre:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: Build Docker image 
        run: |
          docker build -t my-app:latest
      - name:  Run Docker container 
        run: |
          docker run --rm my-app:latest
      
          

          

        
